version = 1

exclude_patterns = [
    "assets/**,",
    "src/basilisk/**",
    "tools/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "2018"
  module_system = "commonjs"
  environment = ["nodejs"]
  style_guide = "airbnb"